#!/usr/bin/env ruby
require "rubygems"
require "thor"

require File.expand_path("../../lib/generators/offsite_payments/integration_generator", __FILE__)

class Generate < Thor
  register(OffsitePayments::Generators::IntegrationGenerator, "integration", "integration NAME", "Generates a new integration.")
end

Generate.start
